### PR TITLE
Start, stop and restart conductr service

### PR DESCRIPTION
**Pull request by markusjura**
Added documentation how manage the conductr and conductr-haproxy service. Also explained how to restart conductr sequiantially in order to avoid split brain scenarios.

This documentation references to the issue: https://github.com/typesafehub/conductr/issues/651

### CODE REVIEW

**Comment by huntc** [comment]
Thanks Markus. Re removing the seed node file, you should only need to remove one of them... And then restart that same node. Restarting subsequent nodes shouldn't require you to remove that file. We should also highlight that you only need to do this in the face of disaster where you've lost the entire cluster. I don't want people to think it is the norm as restarting a cluster this loses all bundle info.

**Comment by markusjura** [comment]
Agree. I think it is best if you add these changes and afterwards merge this PR. Otherwise the communication will go probably back and forth again.

**Comment by huntc** [comment]
It'd be great if you could give it a go. I'm down on resources at present. Cheers.

**Comment by huntc** [comment]
@markusjura It'd be great if we could get this merged/closed. :-)

**Comment by markusjura** [comment]
Yes, will work on that next Monday.

**Comment by markusjura** [comment]
Changed the documentation accordingly.

@huntc : Please review and merge.

**Pull request merged**
