### PR TITLE
DO NOT MERGE UNTIL 1.1.6 IS RELEASED - Release notes for 1.1.6

### PR DESCRIPTION
**Pull request by huntc**

### CODE REVIEW

**Comment by edwardcallahan** [comment]
LGTM

**Comment by edwardcallahan** [comment]
Oh, should we do anything for sigar wrt install/setup requirements?

**Comment by huntc** [comment]
Nothing required - it is setup automatically. :-)

**Comment by edwardcallahan** [comment]
Thanks, that is what I thought.

**Pull request merged**
