### PR TITLE
Relocate release notes

### PR DESCRIPTION
**Pull request by huntc**
Relocate release notes for improved discovery - and also rename the intro section to "General" as it is really a section for both ops and devs.

### CODE REVIEW

**Comment by markusjura** [comment]
Can you rename the `introduction` folder to `general`. Otherwise LGTM.

**Comment by huntc** [comment]
I was avoiding the breaking of external links...

**Comment by huntc** [comment]
Relocated /introduction to /general

**Comment by markusjura** [comment]
LGTM

**Comment by huntc** [comment]
https://github.com/typesafehub/conductr-doc/pull/121 takes care of master

**Pull request merged**
