### PR TITLE
Bundle Housekeeping + Logs

### PR DESCRIPTION
**Pull request by fsat**
* [x] Document log files, log rotation, and custom locations of the log files
* [x] Document bundle housekeeping

### CODE REVIEW

**Comment by fsat** [comment]
Addresses https://github.com/typesafehub/conductr/issues/1607 and https://github.com/typesafehub/conductr/issues/1608

**Comment by fsat** [comment]
[Document bundle housekeeping configuration](https://trello.com/c/V9gWnDyK/526-document-bundle-housekeeping-configuration)

**Comment by fsat** [comment]
[Optionally specify log file dir as part of RPM and Debian images.](https://trello.com/c/stypK3sm/527-optionally-specify-log-file-dir-as-part-of-rpm-and-debian-images)

**Review by huntc — APPROVED** [review]

**Comment by longmuir** [comment]
This looks good - well written. Thanks for adding!

**Review by longmuir — APPROVED** [review]

**Pull request merged**
